'use strict';
const crypto = require('crypto');
const { ApplicationDataStore } = require('./ApplicationDataStore');
const ALLOWED_MIME = new Set(['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime']); const MAX_BYTES = 524288000;
const uuid = () => crypto.randomUUID(); const hash = (value) => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const requireValue = (value, label) => { if (value === undefined || value === null || value === '') throw Object.assign(new Error(`${label} is required.`), { status: 400, code: 'APP_VALIDATION_ERROR' }); return value; };
const appError = (message, code = 'APP_VALIDATION_ERROR', status = 400) => Object.assign(new Error(message), { code, status });
class SupabaseApplicationDataStore extends ApplicationDataStore {
  constructor({ url = process.env.RX_APP_SUPABASE_URL, serviceRoleKey = process.env.RX_APP_SUPABASE_SERVICE_ROLE_KEY, fetchImpl = fetch } = {}) { super(); if (!url || !serviceRoleKey) throw new Error('RX_APP_SUPABASE_URL and RX_APP_SUPABASE_SERVICE_ROLE_KEY are required server-side.'); this.url = url.replace(/\/$/, ''); this.key = serviceRoleKey; this.fetch = fetchImpl; }
  async request(path, options = {}) { const response = await this.fetch(`${this.url}${path}`, { ...options, headers: { apikey: this.key, authorization: `Bearer ${this.key}`, 'content-type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok) { const conflict = body?.code === '40001' || /APP_REVISION_CONFLICT|APP_IDEMPOTENCY_KEY_CONFLICT/i.test(body?.message || ''); throw Object.assign(new Error(body?.message || body?.error || `Supabase request failed (${response.status}).`), { status: conflict ? 409 : response.status, code: conflict ? 'APP_REVISION_CONFLICT' : body?.code }); } return body; }
  rpc(name, args) { return this.request(`/rest/v1/rpc/${name}`, { method: 'POST', body: JSON.stringify(args) }); }
  rows(table, query) { return this.request(`/rest/v1/${table}?${query}`); }
  async byLegacy(table, legacyId) { return (await this.rows(table, `legacy_id=eq.${encodeURIComponent(requireValue(legacyId, 'legacy_id'))}&select=*`))[0] || null; }
  async simpleSave(table, idColumn, legacyId, expectedRevision, body) { const current = await this.byLegacy(table, legacyId); if (!current) { if (expectedRevision !== 0) throw appError('APP_REVISION_CONFLICT', 'APP_REVISION_CONFLICT', 409); return (await this.request(`/rest/v1/${table}`, { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(body) }))[0]; } if (!Number.isInteger(expectedRevision) || expectedRevision < 1) throw appError('APP_REVISION_CONFLICT', 'APP_REVISION_CONFLICT', 409); const rows = await this.request(`/rest/v1/${table}?${idColumn}=eq.${encodeURIComponent(current[idColumn])}&revision=eq.${expectedRevision}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ ...body, revision: expectedRevision + 1, updated_at: new Date().toISOString() }) }); if (!rows.length) throw appError('APP_REVISION_CONFLICT', 'APP_REVISION_CONFLICT', 409); return rows[0]; }
  listCampaigns(kind) { return this.request(`/rest/v1/app_campaigns?select=campaign_id,legacy_id,kind,title,active,folder_id,profile_id,data,revision,created_at,updated_at,app_campaign_posts(post_id,day,text,active,data,revision,app_post_media(ordinal,app_media_objects(media_id,original_name,mime_type,byte_size,state)))&kind=eq.${encodeURIComponent(kind)}&order=title.asc`); } listPosts(campaignId) { return this.request(`/rest/v1/app_campaign_posts?campaign_id=eq.${encodeURIComponent(campaignId)}&select=post_id,day,text,active,data&order=day.asc`); }
  saveCampaign({ campaign, posts, expectedRevision = 0, requestId = uuid() }) { requireValue(campaign?.legacy_id, 'campaign.legacy_id'); requireValue(campaign?.kind, 'campaign.kind'); requireValue(campaign?.title, 'campaign.title'); if (!['property', 'job'].includes(campaign.kind) || !Array.isArray(posts)) throw appError('Invalid campaign snapshot.'); return this.rpc('rx_app_write_campaign_with_posts', { p_campaign: campaign, p_posts: posts, p_expected_revision: expectedRevision, p_request_id: requestId, p_request_hash: hash({ campaign, posts, expectedRevision }) }); }
  savePost(value) { return this.saveCampaign(value); }
  listTargets() { return this.request('/rest/v1/app_targets?select=*&order=display_name.asc'); }
  saveTarget({ legacy_id, display_name, target_url, external_id = null, category = 'Romania', active = true, data = {}, expectedRevision = 0 }) { requireValue(display_name, 'display_name'); requireValue(target_url, 'target_url'); const body = { legacy_id, display_name, target_url, external_id, category, active, data }; return this.simpleSave('app_targets', 'target_id', legacy_id, expectedRevision, body); }
  listCampaignFolders() { return this.request('/rest/v1/app_campaign_folders?select=*&order=name.asc'); } listScheduleFolders() { return this.request('/rest/v1/app_schedule_folders?select=*&order=name.asc'); }
  async saveFolder(table, { legacy_id, name }) { const current = await this.byLegacy(table, legacy_id); if (current) return current; return (await this.request(`/rest/v1/${table}`, { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ legacy_id, name: requireValue(name, 'name') }) }))[0]; }
  saveCampaignFolder(folder) { return this.saveFolder('app_campaign_folders', folder); } saveScheduleFolder(folder) { return this.saveFolder('app_schedule_folders', folder); }
  listSchedules() { return this.request('/rest/v1/app_schedules?select=schedule_id,legacy_id,name,enabled,folder_id,profile_id,schedule,revision,created_at,updated_at,app_schedule_campaigns(ordinal,app_campaigns(campaign_id,legacy_id,kind))&order=name.asc'); }
  listMedia() { return this.request('/rest/v1/app_media_objects?select=media_id,original_name,mime_type,byte_size,state,created_at,app_post_media(post_id)&state=neq.DELETED&order=created_at.desc'); }
  saveSchedule({ schedule, campaignIds, expectedRevision = 0, requestId = uuid() }) { requireValue(schedule?.legacy_id, 'schedule.legacy_id'); requireValue(schedule?.name, 'schedule.name'); if (!Array.isArray(campaignIds)) throw appError('campaignIds must be an array.'); return this.rpc('rx_app_write_schedule_with_campaigns', { p_schedule: schedule, p_campaign_ids: campaignIds, p_expected_revision: expectedRevision, p_request_id: requestId, p_request_hash: hash({ schedule, campaignIds, expectedRevision }) }); }
  async getMedia(mediaId) { return (await this.request(`/rest/v1/app_media_objects?media_id=eq.${encodeURIComponent(mediaId)}&select=*,app_post_media(post_id)&limit=1`))[0] || null; } findMediaByHash(sha256) { return this.request(`/rest/v1/app_media_objects?sha256=eq.${encodeURIComponent(requireValue(sha256, 'sha256'))}&state=neq.DELETED&select=*&order=created_at.asc`); }
  async saveMediaMetadata({ sha256, byte_size, mime_type, original_name, object_key, state = 'STAGED' }) { if (!/^[a-f0-9]{64}$/.test(sha256 || '') || !Number.isInteger(byte_size) || byte_size < 1 || !ALLOWED_MIME.has(mime_type)) throw appError('Invalid immutable media metadata.'); const existing = await this.findMediaByHash(sha256); if (existing.length) return existing[0]; const original = String(original_name || 'media').replace(/[^A-Za-z0-9._-]/g, '_').slice(-160) || 'media'; return (await this.request('/rest/v1/app_media_objects', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ media_id: uuid(), bucket: 'fam-app-media', object_key: object_key || `import/${sha256}/${original}`, sha256, byte_size, mime_type, original_name: original, state }) }))[0]; }
  setPostMedia({ postId, mediaIds, expectedRevision, requestId = uuid() }) { if (!Array.isArray(mediaIds)) throw appError('mediaIds must be an array.'); return this.rpc('rx_app_set_post_media', { p_post_id: postId, p_media_ids: mediaIds, p_expected_revision: expectedRevision, p_request_id: requestId, p_request_hash: hash({ postId, mediaIds, expectedRevision }) }); }
  async createExecutionRun(run) { const current = await this.byLegacy('app_execution_runs', run?.legacy_id); if (current) return current; return (await this.request('/rest/v1/app_execution_runs', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(run) }))[0]; }
  async recordPostingResult(result) { if (result.task_id) { const existing = await this.rows('app_posting_results', `task_id=eq.${encodeURIComponent(result.task_id)}&select=*`); if (existing[0]) return existing[0]; } return (await this.request('/rest/v1/app_posting_results', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(result) }))[0]; }
  async initiateMedia({ originalName, mimeType, byteSize, sha256, requestId }) { if (!ALLOWED_MIME.has(mimeType) || !Number.isInteger(byteSize) || byteSize < 1 || byteSize > MAX_BYTES || !/^[a-f0-9]{64}$/.test(sha256 || '')) throw appError('Invalid immutable media metadata.'); if ((await this.findMediaByHash(sha256)).length) throw appError('An immutable media identity already exists for this SHA-256.', 'APP_MEDIA_IDENTITY_EXISTS', 409); const media = await this.saveMediaMetadata({ original_name: originalName, mime_type: mimeType, byte_size: byteSize, sha256 }); const objectPath = encodeURIComponent(media.object_key).replace(/%2F/g, '/'); const signed = await this.request(`/storage/v1/object/upload/sign/${media.bucket}/${objectPath}`, { method: 'POST', headers: { 'x-rx-request-id': requestId || uuid() }, body: JSON.stringify({}) }); return { media: { media_id: media.media_id, bucket: media.bucket, object_key: media.object_key, state: media.state, byte_size: media.byte_size, mime_type: media.mime_type }, upload: { url: signed.url?.startsWith('http') ? signed.url : `${this.url}/storage/v1${signed.url}`, token: signed.token }, expires_in: 120 }; }
  async verifiedObjectBytes(media) { const response = await this.fetch(`${this.url}/storage/v1/object/${media.bucket}/${encodeURIComponent(media.object_key).replace(/%2F/g, '/')}`, { headers: { apikey: this.key, authorization: `Bearer ${this.key}` } }); if (!response.ok || !response.body) throw appError('Uploaded object was not found for verification.', 'APP_MEDIA_OBJECT_MISSING', 409); const digest = crypto.createHash('sha256'); let byteSize = 0; for await (const chunk of response.body) { byteSize += chunk.length; if (byteSize > MAX_BYTES) throw appError('Uploaded object exceeds the media limit.', 'APP_MEDIA_SIZE_MISMATCH', 409); digest.update(chunk); } return { byte_size: byteSize, sha256: digest.digest('hex') }; }
  async finalizeMedia({ mediaId }) { const media = await this.getMedia(mediaId); if (!media || media.state !== 'STAGED') throw appError('Only staged media can be finalized.'); const verified = await this.verifiedObjectBytes(media); if (verified.byte_size !== Number(media.byte_size)) throw appError('Uploaded object byte size does not match immutable metadata.', 'APP_MEDIA_SIZE_MISMATCH', 409); if (verified.sha256 !== media.sha256) throw appError('Uploaded object SHA-256 does not match immutable metadata.', 'APP_MEDIA_HASH_MISMATCH', 409); const rows = await this.request(`/rest/v1/app_media_objects?media_id=eq.${encodeURIComponent(mediaId)}&state=eq.STAGED`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ state: 'READY' }) }); if (!rows.length) throw appError('Media finalization race detected.', 'APP_MEDIA_FINALIZATION_RACE', 409); return { media: rows[0], verification: { byte_size: verified.byte_size, sha256: verified.sha256 } }; }
  async createPreview(mediaId) { const media = await this.getMedia(mediaId); if (!media || media.state !== 'READY' || !media.app_post_media?.length) throw appError('Media is not authorized for preview.', 'NOT_FOUND', 404); const signed = await this.request(`/storage/v1/object/sign/${media.bucket}/${encodeURIComponent(media.object_key).replace(/%2F/g, '/')}`, { method: 'POST', body: JSON.stringify({ expiresIn: 120 }) }); const value = signed.signedURL || signed.signedUrl || signed.url; if (!value) throw appError('Media preview could not be authorized.', 'APP_MEDIA_PREVIEW_UNAVAILABLE', 404); const url = /^https?:\/\//i.test(value) ? value : `${this.url}/storage/v1${value.startsWith('/storage/v1/') ? value.slice('/storage/v1'.length) : value}`; return { url, expiresIn: 120 }; }
}
module.exports = { SupabaseApplicationDataStore, ALLOWED_MIME, MAX_BYTES };
