'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const http = require('node:http');
const express = require('express');
const { createHostedBffApp } = require('../server/hosted-bff');
const { createCloudRemoteTaskRouter, safeTask } = require('../server/cloud-remote-task-api');

const origin = 'http://127.0.0.1:5173'; const password = 'remote task password'; const salt = Buffer.alloc(16, 7);
const passwordHash = `scrypt$16384$8$1$${salt.toString('hex')}$${crypto.scryptSync(password, salt, 64, { N: 16384, r: 8, p: 1, maxmem: 256 * 1024 * 1024 }).toString('hex')}`;
const userPassword = 'user remote password'; const userSalt = Buffer.alloc(16, 8);
const userPasswordHash = `scrypt$16384$8$1$${userSalt.toString('hex')}$${crypto.scryptSync(userPassword, userSalt, 64, { N: 16384, r: 8, p: 1, maxmem: 256 * 1024 * 1024 }).toString('hex')}`;
const agentId = 'agent_SYNTHETIC'; const profileId = 'profile_SYNTHETIC';
const env = (enabled = true, options = {}) => ({ NODE_ENV: 'test', AUTH_ENABLED: 'true', ADMIN_PASSWORD_SCRYPT: passwordHash, USER_USERNAME: 'user', USER_PASSWORD_SCRYPT: userPasswordHash, RX_BFF_SESSION_SIGNING_SECRET: 'remote-task-test-signing-secret-that-is-long-enough', RX_BFF_ALLOWED_ORIGINS: origin, RX_BFF_CLOUD_REMOTE_TASKS_ENABLED: enabled ? 'true' : 'false', RX_BFF_CHROMIUM_PREFLIGHT_ENABLED: options.chromiumPreflightEnabled ? 'true' : 'false', RX_BFF_CONTROLLED_EXECUTION_ENABLED: options.controlledExecutionEnabled ? 'true' : 'false', RX_BFF_SYNTHETIC_AGENT_ID: options.configuredAgentId ?? agentId, RX_BFF_SYNTHETIC_PROFILE_ID: options.configuredProfileId ?? profileId });

function store({ online = true, agentExists = true, profileExists = true, ownershipCorrect = true, profileReady = true, activeProfileId = '' } = {}) {
  const tasks = new Map(); let creates = 0;
  const now = new Date().toISOString();
  const agents = new Map([
    [agentId, agentExists ? (online ? { agent_id: agentId, reported_status: 'ONLINE', last_seen_at: now } : { agent_id: agentId, reported_status: 'OFFLINE', last_seen_at: new Date(0).toISOString() }) : null],
    ['agent_A', { agent_id: 'agent_A', reported_status: 'ONLINE', last_seen_at: now }],
    ['agent_B', { agent_id: 'agent_B', reported_status: 'BUSY', last_seen_at: now }],
    ['agent_C', { agent_id: 'agent_C', reported_status: 'ONLINE', last_seen_at: new Date(0).toISOString() }],
    ['agent_D', { agent_id: 'agent_D', reported_status: 'OFFLINE', last_seen_at: now }],
  ]);
  const profiles = new Map([
    [profileId, profileExists ? { profile_id: profileId, agent_id: ownershipCorrect ? agentId : 'agent_OTHER', status: profileReady ? 'READY' : 'ERROR' } : null],
    ['profile_A', { profile_id: 'profile_A', agent_id: 'agent_A', status: 'READY' }],
    ['profile_A_ERROR', { profile_id: 'profile_A_ERROR', agent_id: 'agent_A', status: 'ERROR' }],
    ['profile_B', { profile_id: 'profile_B', agent_id: 'agent_B', status: 'READY' }],
    ['profile_C', { profile_id: 'profile_C', agent_id: 'agent_C', status: 'READY' }],
    ['profile_D', { profile_id: 'profile_D', agent_id: 'agent_D', status: 'READY' }],
  ]);
  const source = {
    campaign: { campaign_id: '11111111-1111-4111-8111-111111111111', legacy_id: 'campaign-safe', kind: 'property', active: true, profile_id: 'profile-reference', revision: 4, app_campaign_posts: [{ post_id: 'post-uuid', day: 2, text: 'Cloud snapshot text', active: true, revision: 3, app_post_media: [{ ordinal: 1, app_media_objects: { media_id: 'media-two', sha256: 'b'.repeat(64), byte_size: 2, mime_type: 'image/png', state: 'READY' } }, { ordinal: 0, app_media_objects: { media_id: 'media-one', sha256: 'a'.repeat(64), byte_size: 1, mime_type: 'image/png', state: 'READY' } }] }] },
    target: { target_id: '22222222-2222-4222-8222-222222222222', legacy_id: 'target-safe', display_name: 'Synthetic target', target_url: 'https://example.test/group', active: true },
  };
  return { creates: () => creates, task: () => [...tasks.values()][0],
    listManagedUserExecutionTargets: async (userId, { enabledOnly } = {}) => userId === '11111111-1111-4111-8111-111111111111' ? [{ user_id: userId, device_id: 'agent_A', profile_id: 'profile_A', enabled: true }] : [],
    getControlPlaneAgent: async (requestedAgentId) => agents.get(requestedAgentId) || null,
    getControlPlaneProfile: async (requestedProfileId) => profiles.get(requestedProfileId) || null,
    getActiveControlPlaneTaskForProfile: async (requestedProfileId) => requestedProfileId === activeProfileId ? { task_id: 'active-task' } : null,
    getCampaignPreflightSource: async ({ kind, campaignId, targetId }) => ({ campaign: kind === 'property' && campaignId === source.campaign.campaign_id ? source.campaign : null, target: targetId === source.target.target_id ? source.target : null }),
    getCampaignPreflightSourceForManagedUser: async ({ kind, campaignId, targetId }) => ({ campaign: kind === 'property' && campaignId === source.campaign.campaign_id ? source.campaign : null, target: targetId === source.target.target_id ? source.target : null }),
    createControlPlaneTask: async (task) => { creates += 1; const row = { ...task, status: 'QUEUED', created_at: new Date().toISOString(), result: null }; tasks.set(task.task_id, row); return row; },
    getControlPlaneTask: async (id) => tasks.get(id) || null,
    listControlPlaneTaskEvents: async (id) => tasks.has(id) ? [{ event_type: 'TASK_CLAIMED', occurred_at: '2026-09-09T00:00:00Z' }, { event_type: 'TASK_RUNNING', occurred_at: '2026-09-09T00:00:01Z' }, { event_type: 'TASK_COMPLETED', occurred_at: '2026-09-09T00:00:02Z' }] : [],
  };
}
async function fixture(run, options = {}) { const memory = store(options); const server = http.createServer(createHostedBffApp({ env: env(options.enabled, options), store: memory })); await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve)); const base = `http://127.0.0.1:${server.address().port}`; const request = async (path, { method = 'GET', body, cookie, csrf, requestOrigin = method === 'GET' ? undefined : origin } = {}) => { const response = await fetch(`${base}${path}`, { method, headers: { ...(body !== undefined ? { 'content-type': 'application/json' } : {}), ...(cookie ? { cookie } : {}), ...(csrf ? { 'x-rx-csrf': csrf } : {}), ...(requestOrigin ? { origin: requestOrigin } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) }); const setCookie = response.headers.getSetCookie?.()[0] || response.headers.get('set-cookie') || ''; return { response, body: await response.json().catch(() => ({})), cookie: setCookie.split(';')[0] }; }; try { await run({ request, memory }); } finally { await new Promise((resolve) => server.close(resolve)); } }

test('remote synthetic task capability is disabled by default', async () => { await fixture(async ({ request }) => { assert.equal((await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {} })).response.status, 404); }, { enabled: false }); });
test('remote synthetic task requires session, CSRF, and approved origin', async () => { await fixture(async ({ request, memory }) => { assert.equal((await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {} })).response.status, 401); const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; assert.equal((await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {}, cookie: auth.cookie })).response.status, 403); assert.equal((await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {}, ...auth, requestOrigin: 'https://attacker.test' })).response.status, 403); assert.equal(memory.creates(), 0); }); });
const campaignId = '11111111-1111-4111-8111-111111111111'; const targetId = '22222222-2222-4222-8222-222222222222';
test('USER cannot invoke privileged remote preflight routes', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'user', password: userPassword, role: 'ADMIN' } }); assert.equal(login.body.role, 'USER'); const result = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body: { kind: 'property', campaignId, day: 2, targetId }, cookie: login.cookie, csrf: login.body.csrfToken }); assert.equal(result.response.status, 403); assert.equal(memory.creates(), 0); }); });
test('internal managed-user creation stamps the session user and ignores browser ownership injection', async () => {
  const memory = store(); const ownerA = '11111111-1111-4111-8111-111111111111'; const ownerB = '22222222-2222-4222-8222-222222222222';
  const app = express(); app.use(express.json()); app.use((req, res, next) => { req.user = { role: 'USER', managedUserId: ownerA }; next(); }); app.use(createCloudRemoteTaskRouter({ store: memory, agentId, profileId }));
  const server = http.createServer(app); await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  try {
    const response = await fetch(`http://127.0.0.1:${server.address().port}/campaign-preflight`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind: 'property', campaignId, day: 2, targetId, deviceId: 'agent_A', profileId: 'profile_A', owner_user_id: ownerB, ownerUserId: ownerB, createdByUserId: ownerB, username: 'other', role: 'ADMIN' }) });
    assert.equal(response.status, 201); assert.equal(memory.task().owner_user_id, ownerA);
  } finally { await new Promise((resolve) => server.close(resolve)); }
});
test('server creates one fixed DRY_RUN task and exposes only safe readback', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const created = await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: { agentId: 'agent_ATTACKER', profileId: 'profile_ATTACKER', taskType: 'FACEBOOK_GROUP_POST', payload: { publishEnabled: true } }, ...auth }); assert.equal(created.response.status, 201); assert.equal(memory.creates(), 1); assert.match(created.body.task.taskId, /^synthetic_dry_run_/); assert.deepEqual(Object.keys(created.body.task).sort(), ['claimedAt', 'completedAt', 'createdAt', 'result', 'startedAt', 'status', 'taskId']); assert.equal(created.body.task.status, 'QUEUED'); assert.equal(JSON.stringify(created.body).match(/agent|profile|payload|lease|secret/i), null); const read = await request(`/api/cloud-remote-tasks/synthetic-dry-run/${created.body.task.taskId}`, { cookie: auth.cookie }); assert.equal(read.response.status, 200); assert.deepEqual(read.body.events.map((event) => event.type), ['TASK_CLAIMED', 'TASK_RUNNING', 'TASK_COMPLETED']); assert.equal((await request('/api/cloud-remote-tasks/synthetic-dry-run/not-synthetic', { cookie: auth.cookie })).response.status, 404); }); });
test('trims configured synthetic target IDs before validating a proven-ready target', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const created = await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {}, cookie: login.cookie, csrf: login.body.csrfToken }); assert.equal(created.response.status, 201); assert.equal(memory.creates(), 1); }, { configuredAgentId: `\r\n ${agentId} \t`, configuredProfileId: ` ${profileId}\n` }); });
test('general campaign preflight validates exact browser-selected device/profile routing and server-builds the task', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const created = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body: { kind: 'property', campaignId, day: 2, targetId, campaignRevision: 4, postRevision: 3, deviceId: 'agent_A', profileId: 'profile_A', taskType: 'FACEBOOK_GROUP_POST', publishEnabled: true, payload: { publishEnabled: true, cookies: 'forbidden' } }, ...auth }); assert.equal(created.response.status, 201); assert.equal(created.body.task.status, 'QUEUED'); assert.equal(memory.creates(), 1); assert.equal(JSON.stringify(created.body).match(/payload|agent_A|profile_A|cookie|secret/i), null); assert.deepEqual({ agentId: memory.task().agent_id, profileId: memory.task().profile_id, taskType: memory.task().task_type, mode: memory.task().payload.mode, publishEnabled: memory.task().payload.publishEnabled }, { agentId: 'agent_A', profileId: 'profile_A', taskType: 'CAMPAIGN_PREFLIGHT', mode: 'PREFLIGHT', publishEnabled: false }); const read = await request(`/api/cloud-remote-tasks/campaign-preflight/${created.body.task.taskId}`, { cookie: auth.cookie }); assert.equal(read.response.status, 200); assert.equal(read.body.task.result, null); }); });
test('controlled execution is separately gated, ADMIN-only, immutable, and never accepts browser publishing input', async () => { await fixture(async ({ request, memory }) => { const admin = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: admin.cookie, csrf: admin.body.csrfToken }; const body = { kind: 'property', campaignId, day: 2, targetId, deviceId: 'agent_A', profileId: 'profile_A', taskType: 'FACEBOOK_GROUP_POST', publishEnabled: true, owner_user_id: 'attacker', payload: { local_media_paths: ['C:/bad'], publishEnabled: true } }; assert.equal((await request('/api/cloud-remote-tasks/controlled-execution', { method: 'POST', body, ...auth })).response.status, 404); assert.equal(memory.creates(), 0); }, { controlledExecutionEnabled: false }); await fixture(async ({ request, memory }) => { const user = await request('/api/auth/login', { method: 'POST', body: { username: 'user', password: userPassword } }); const body = { kind: 'property', campaignId, day: 2, targetId, deviceId: 'agent_A', profileId: 'profile_A' }; assert.equal((await request('/api/cloud-remote-tasks/controlled-execution', { method: 'POST', body, cookie: user.cookie, csrf: user.body.csrfToken })).response.status, 403); const admin = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: admin.cookie, csrf: admin.body.csrfToken }; const created = await request('/api/cloud-remote-tasks/controlled-execution', { method: 'POST', body: { ...body, publishEnabled: true, payload: { cookies: 'bad' } }, ...auth }); assert.equal(created.response.status, 201); assert.equal(memory.task().task_type, 'CONTROLLED_CAMPAIGN_EXECUTION'); assert.equal(memory.task().payload.mode, 'CONTROLLED_DRY_EXECUTION'); assert.equal(memory.task().payload.publishEnabled, false); assert.equal(JSON.stringify(memory.task().payload).match(/local_media_paths|cookies/i), null); const replay = await request('/api/cloud-remote-tasks/controlled-execution', { method: 'POST', body, ...auth }); assert.equal(replay.response.status, 200); assert.equal(memory.creates(), 1); }, { controlledExecutionEnabled: true }); });
test('hosted campaign preflight accepts only canonical UUID source identifiers and never falls back to legacy IDs', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const base = { kind: 'property', day: 2, deviceId: 'agent_A', profileId: 'profile_A' }; const canonical = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body: { ...base, campaignId, targetId }, ...auth }); assert.equal(canonical.response.status, 201); assert.equal(memory.creates(), 1); for (const body of [{ ...base, campaignId: 'campaign-safe', targetId }, { ...base, campaignId, targetId: 'target-safe' }]) { const rejected = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body, ...auth }); assert.equal(rejected.response.status, 400); assert.match(rejected.body.code, /^INVALID_(CAMPAIGN|TARGET)_ID$/); } assert.equal(memory.creates(), 1); }); });
test('general campaign preflight accepts exact ready pairs, rejects cross-device/stale/unavailable pairs, and never falls back', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const submit = async (deviceId, profileId) => request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body: { kind: 'property', campaignId, day: 2, targetId, campaignRevision: 4, postRevision: 3, deviceId, profileId }, ...auth });
  assert.equal((await submit('agent_A', 'profile_A')).response.status, 201);
  assert.equal((await submit('agent_B', 'profile_B')).response.status, 201);
  for (const [deviceId, profileId, code] of [['agent_A', 'profile_B', 'PROFILE_OWNERSHIP_MISMATCH'], ['agent_B', 'profile_A', 'PROFILE_OWNERSHIP_MISMATCH'], ['agent_C', 'profile_C', 'DEVICE_STALE'], ['agent_D', 'profile_D', 'DEVICE_OFFLINE'], ['agent_UNKNOWN', 'profile_A', 'DEVICE_NOT_FOUND'], ['agent_A', 'profile_UNKNOWN', 'PROFILE_NOT_FOUND'], ['agent_A', 'profile_A_ERROR', 'PROFILE_NOT_READY']]) { const result = await submit(deviceId, profileId); assert.equal(result.response.status, 409); assert.equal(result.body.code, code); }
  assert.equal(memory.creates(), 2);
}, { configuredAgentId: '', configuredProfileId: '' }); });
test('general campaign preflight is server-idempotent and reports an active profile conflict before queuing', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const body = { kind: 'property', campaignId, day: 2, targetId, campaignRevision: 4, postRevision: 3, deviceId: 'agent_A', profileId: 'profile_A' }; const first = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body, ...auth }); const replay = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body, ...auth }); assert.equal(first.response.status, 201); assert.equal(replay.response.status, 200); assert.equal(replay.body.task.taskId, first.body.task.taskId); assert.equal(memory.creates(), 1); }); await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const result = await request('/api/cloud-remote-tasks/campaign-preflight', { method: 'POST', body: { kind: 'property', campaignId, day: 2, targetId, deviceId: 'agent_A', profileId: 'profile_A' }, cookie: login.cookie, csrf: login.body.csrfToken }); assert.equal(result.response.status, 409); assert.equal(result.body.code, 'CONFLICTING_WORK'); assert.equal(memory.creates(), 0); }, { activeProfileId: 'profile_A' }); });
test('remote target reports only safe availability flags for an administrator', async () => { await fixture(async ({ request }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const diagnostic = await request('/api/cloud-remote-tasks/synthetic-dry-run/availability', { cookie: login.cookie }); assert.equal(diagnostic.response.status, 200); assert.deepEqual(diagnostic.body, { agentConfigured: true, profileConfigured: true, ownershipCorrect: true, profileReady: true, agentStatusAccepted: true, heartbeatFresh: true }); assert.equal(JSON.stringify(diagnostic.body).match(/agent_SYNTHETIC|profile_SYNTHETIC|secret|lease|payload/i), null); }); });
for (const [name, options, code] of [
  ['agent is absent', { agentExists: false }, 'SYNTHETIC_AGENT_NOT_FOUND'],
  ['profile is absent', { profileExists: false }, 'SYNTHETIC_PROFILE_NOT_FOUND'],
  ['profile ownership differs', { ownershipCorrect: false }, 'SYNTHETIC_PROFILE_OWNERSHIP_MISMATCH'],
]) test(`remote target classifies safely when ${name}`, async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const result = await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {}, cookie: login.cookie, csrf: login.body.csrfToken }); assert.equal(result.response.status, 409); assert.deepEqual(result.body, { error: 'Configured synthetic agent/profile is unavailable.', code }); assert.equal(memory.creates(), 0); }, options); });
test('offline synthetic agent is rejected without queuing a task', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const result = await request('/api/cloud-remote-tasks/synthetic-dry-run', { method: 'POST', body: {}, cookie: login.cookie, csrf: login.body.csrfToken }); assert.equal(result.response.status, 409); assert.equal(memory.creates(), 0); }, { online: false }); });
test('Chromium preflight is independently disabled and accepts no browser-controlled payload', async () => { await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const disabled = await request('/api/cloud-remote-tasks/chromium-safe-preflight', { method: 'POST', body: {}, ...auth }); assert.equal(disabled.response.status, 404); assert.equal(memory.creates(), 0); }, { chromiumPreflightEnabled: false }); await fixture(async ({ request, memory }) => { const login = await request('/api/auth/login', { method: 'POST', body: { username: 'admin', password } }); const auth = { cookie: login.cookie, csrf: login.body.csrfToken }; const created = await request('/api/cloud-remote-tasks/chromium-safe-preflight', { method: 'POST', body: { profileId: 'attacker', url: 'https://facebook.com/', executablePath: 'bad', publishEnabled: true }, ...auth }); assert.equal(created.response.status, 201); assert.equal(memory.creates(), 1); assert.match(created.body.task.taskId, /^chromium_safe_preflight_/); assert.equal(JSON.stringify(created.body).match(/attacker|facebook|payload|profile|lease|secret/i), null); }, { chromiumPreflightEnabled: true }); });
test('Chromium safe task preserves every verified postcondition in its browser-safe DTO', () => {
  const raw = { preflight_passed: true, chromium_launched: true, page_ready: true, safe_navigation: true, browser_closed: true, profile_lock_released: true, publishEnabled: false, blockers: [], profile_path: 'must-not-leak', cookies: 'must-not-leak' };
  assert.deepEqual(safeTask({ task_id: 'chromium_safe_preflight_fixture', task_type: 'CHROMIUM_SAFE_PREFLIGHT', status: 'COMPLETED', result: raw }), { taskId: 'chromium_safe_preflight_fixture', status: 'COMPLETED', createdAt: null, claimedAt: null, startedAt: null, completedAt: null, result: { preflightPassed: true, chromiumLaunched: true, pageReady: true, safeNavigation: true, browserClosed: true, profileLockReleased: true, publishEnabled: false, blockers: [] } });
});
test('incomplete or failed Chromium postconditions never appear as a successful safe result', () => {
  const raw = { preflight_passed: true, chromium_launched: true, page_ready: true, safe_navigation: false, browser_closed: true, profile_lock_released: true, publishEnabled: false, blockers: [] };
  assert.equal(safeTask({ task_id: 'chromium_safe_preflight_incomplete', task_type: 'CHROMIUM_SAFE_PREFLIGHT', status: 'COMPLETED', result: raw }).result, null);
});
