'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const express = require('express'); const http = require('node:http'); const fs = require('node:fs'); const path = require('node:path');
const { createCloudDashboardReadRouter } = require('../server/cloud-dashboard-read-api'); const { createCloudRemoteTaskRouter } = require('../server/cloud-remote-task-api');
const ownerA = '11111111-1111-4111-8111-111111111111'; const ownerB = '22222222-2222-4222-8222-222222222222'; const now = new Date().toISOString();
test('G3 migration is explicit, unique, restrictive, and service-role-only', () => { const sql = fs.readFileSync(path.join(__dirname, '..', 'supabase', 'migrations', '202609100002_hosted_user_execution_targets.sql'), 'utf8'); assert.match(sql, /hosted_user_execution_targets/); assert.match(sql, /references public\.hosted_users/); assert.match(sql, /unique \(user_id, device_id, profile_id\)/); assert.match(sql, /enable row level security/); assert.match(sql, /revoke all.*anon, authenticated/); assert.match(sql, /service_role/); });
test('managed USER target reads and routed preflight are allowlisted, owner-stamped, and owner-idempotent', async () => {
  const targets = [{ user_id: ownerA, device_id: 'agent-a', profile_id: 'profile-a', enabled: true }, { user_id: ownerB, device_id: 'agent-b', profile_id: 'profile-b', enabled: true }]; const tasks = new Map();
  const store = {
    listManagedUserExecutionTargets: async (id, { enabledOnly } = {}) => targets.filter((target) => target.user_id === id && (!enabledOnly || target.enabled)),
    listControlPlaneAgents: async () => [{ agent_id: 'agent-a', display_name: 'A', reported_status: 'ONLINE', last_seen_at: now }, { agent_id: 'agent-b', display_name: 'B', reported_status: 'ONLINE', last_seen_at: now }], listControlPlaneProfiles: async () => [{ profile_id: 'profile-a', agent_id: 'agent-a', display_name: 'PA', status: 'READY' }, { profile_id: 'profile-b', agent_id: 'agent-b', display_name: 'PB', status: 'READY' }],
    getControlPlaneAgent: async (id) => (await store.listControlPlaneAgents()).find((item) => item.agent_id === id) || null, getControlPlaneProfile: async (id) => (await store.listControlPlaneProfiles()).find((item) => item.profile_id === id) || null, getActiveControlPlaneTaskForProfile: async () => null,
    getCampaignPreflightSource: async () => ({ campaign: { campaign_id: 'campaign-id', legacy_id: 'campaign', kind: 'property', active: true, revision: 1, app_campaign_posts: [{ post_id: 'post-id', day: 1, active: true, revision: 1, text: 'x', app_post_media: [] }] }, target: { target_id: 'target-id', legacy_id: 'target', display_name: 'Target', active: true, target_url: 'https://example.test' } }), createControlPlaneTask: async (task) => { const row = { ...task, status: 'QUEUED', created_at: now }; tasks.set(task.task_id, row); return row; }, getControlPlaneTask: async (id) => tasks.get(id) || null, listControlPlaneTaskEvents: async () => [],
  };
  const app = express(); app.use(express.json()); app.use((req, _res, next) => { req.user = req.get('x-user') === 'b' ? { role: 'USER', managedUserId: ownerB } : req.get('x-user') === 'admin' ? { role: 'ADMIN' } : { role: 'USER', managedUserId: ownerA }; next(); }); app.use('/read', createCloudDashboardReadRouter(store)); app.use('/remote', createCloudRemoteTaskRouter({ store })); const server = http.createServer(app); await new Promise((resolve) => server.listen(0, resolve)); const base = `http://127.0.0.1:${server.address().port}`; const request = async (url, options = {}) => { const response = await fetch(base + url, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } }); return { response, body: await response.json() }; };
  try { const aTargets = await request('/read/my-execution-targets'); const bTargets = await request('/read/my-execution-targets', { headers: { 'x-user': 'b' } }); assert.deepEqual(aTargets.body.targets.map((target) => target.deviceId), ['agent-a']); assert.deepEqual(bTargets.body.targets.map((target) => target.deviceId), ['agent-b']); const body = { kind: 'property', campaignId: 'campaign', day: 1, targetId: 'target', deviceId: 'agent-a', profileId: 'profile-a', owner_user_id: ownerB, publishEnabled: true, payload: { path: 'forbidden' } }; const created = await request('/remote/campaign-preflight', { method: 'POST', body: JSON.stringify(body) }); assert.equal(created.response.status, 201); assert.equal([...tasks.values()][0].owner_user_id, ownerA); assert.equal([...tasks.values()][0].payload.publishEnabled, false); assert.equal((await request('/remote/campaign-preflight', { method: 'POST', headers: { 'x-user': 'b' }, body: JSON.stringify(body) })).response.status, 403); const replay = await request('/remote/campaign-preflight', { method: 'POST', body: JSON.stringify(body) }); assert.equal(replay.response.status, 200); assert.equal(tasks.size, 1); assert.doesNotMatch(JSON.stringify(aTargets.body), /user_id|assignment_id|secret|path/i); } finally { await new Promise((resolve) => server.close(resolve)); }
});
