import { useEffect, useState } from 'react';
import { api } from '../services/api';
import { credentialCopyText, generateStrongPassword } from '../services/userCredentialHandoff';

function formatDate(value) { return value ? new Intl.DateTimeFormat('ro-RO', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Niciodată'; }

function HostedUsers() {
  const [users, setUsers] = useState([]); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ username: '', password: '', confirm: '' }); const [resetId, setResetId] = useState(null); const [reset, setReset] = useState({ password: '', confirm: '' }); const [handoff, setHandoff] = useState(null); const [handoffMessage, setHandoffMessage] = useState(''); const [showCreatePassword, setShowCreatePassword] = useState(false); const [showResetPassword, setShowResetPassword] = useState(false); const [showHandoffPassword, setShowHandoffPassword] = useState(false);
  async function load() { try { const result = await api.getManagedUsers(); setUsers(result.users || []); setError(''); } catch (loadError) { setError(loadError.message || 'Utilizatorii nu au putut fi încărcați.'); } }
  useEffect(() => { let ignore = false; api.getManagedUsers().then((result) => { if (!ignore) { setUsers(result.users || []); setError(''); } }).catch((loadError) => { if (!ignore) setError(loadError.message || 'Utilizatorii nu au putut fi încărcați.'); }); return () => { ignore = true; }; }, []);
  function generateCreatePassword() { const password = generateStrongPassword(); setForm({ ...form, password, confirm: password }); setShowCreatePassword(true); }
  function generateResetPassword() { const password = generateStrongPassword(); setReset({ password, confirm: password }); setShowResetPassword(true); }
  async function copy(value) { try { if (!navigator.clipboard?.writeText) throw new Error('Clipboard unavailable'); await navigator.clipboard.writeText(value); setHandoffMessage('Copiat'); } catch { setHandoffMessage('Copierea nu a reușit.'); } }
  function dismissHandoff() { setHandoff(null); setHandoffMessage(''); setShowHandoffPassword(false); }
  async function create() { if (form.password !== form.confirm) return setMessage('Parolele nu corespund.'); const password = form.password; try { const result = await api.createManagedUser({ username: form.username, password }); setForm({ username: '', password: '', confirm: '' }); setHandoff({ username: result.user.username, password }); setShowHandoffPassword(false); setHandoffMessage(''); setMessage('Utilizator creat.'); await load(); } catch (createError) { setMessage(createError.message || 'Utilizatorul nu a putut fi creat.'); } }
  async function toggle(user) { try { await api.updateManagedUser(user.userId, { enabled: !user.enabled }); setMessage(user.enabled ? 'Utilizator dezactivat; sesiunile existente au fost invalidate.' : 'Utilizator activat.'); await load(); } catch (updateError) { setMessage(updateError.message || 'Utilizatorul nu a putut fi actualizat.'); } }
  async function resetPassword(userId) { if (reset.password !== reset.confirm) return setMessage('Parolele nu corespund.'); const password = reset.password; try { const result = await api.resetManagedUserPassword(userId, { password }); setResetId(null); setReset({ password: '', confirm: '' }); setHandoff({ username: result.user.username, password }); setShowHandoffPassword(false); setHandoffMessage(''); setMessage('Parolă resetată; sesiunile existente au fost invalidate.'); await load(); } catch (resetError) { setMessage(resetError.message || 'Parola nu a putut fi resetată.'); } }
  return <div className="management-page"><header className="management-header"><div><span className="hero-eyebrow">HOSTED ADMIN</span><h1>Utilizatori</h1><p>Conturi USER cloud-managed. Administratorul bootstrap rămâne configurat server-side.</p></div></header>
    <section className="editor-panel"><h2>Adaugă utilizator</h2><div className="button-row"><input placeholder="username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><input type={showCreatePassword ? 'text' : 'password'} placeholder="parolă" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /><button className="ghost-button" onClick={() => setShowCreatePassword(!showCreatePassword)}>{showCreatePassword ? 'Ascunde parola' : 'Arată parola'}</button><button className="secondary-button" onClick={generateCreatePassword}>Generează</button><input type={showCreatePassword ? 'text' : 'password'} placeholder="confirmă parola" value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} /><button className="primary-button" onClick={create}>Adaugă utilizator</button></div><p className="muted-text">Rol fix: USER. Parola nu este afișată sau păstrată după creare.</p></section>
    {error && <section className="editor-panel"><p className="save-message">{error}</p></section>}{message && <section className="editor-panel"><p className="save-message">{message}</p></section>}{handoff && <section className="editor-panel"><div className="panel-title-row"><div><h2>Date de acces — afișate o singură dată</h2><p className="muted-text">Salvează parola acum. După închiderea acestei ferestre parola nu mai poate fi afișată din nou. Serverul stochează doar hash-ul Scrypt.</p></div><button className="ghost-button" onClick={dismissHandoff}>Închide și șterge</button></div><p>Username: <code>{handoff.username}</code></p><p>Parolă: <code>{showHandoffPassword ? handoff.password : '••••••••••••••••••••'}</code> <button className="ghost-button" onClick={() => setShowHandoffPassword(!showHandoffPassword)}>{showHandoffPassword ? 'Ascunde parola' : 'Arată parola'}</button></p><div className="button-row"><button className="secondary-button" onClick={() => copy(handoff.username)}>Copiază username</button><button className="secondary-button" onClick={() => copy(handoff.password)}>Copiază parola</button><button className="secondary-button" onClick={() => copy(credentialCopyText(handoff))}>Copiază datele</button></div>{handoffMessage && <p className="muted-text">{handoffMessage}</p>}</section>}
    {users.map((user) => <section className="editor-panel" key={user.userId}><div className="panel-title-row"><div><h2>{user.username}</h2><p className="muted-text">USER · creat: {formatDate(user.createdAt)} · ultima autentificare: {formatDate(user.lastLoginAt)}</p></div><span className={`status-pill ${user.enabled ? 'active' : 'inactive'}`}>{user.enabled ? 'ACTIV' : 'DEZACTIVAT'}</span></div><div className="button-row"><button className="secondary-button" onClick={() => toggle(user)}>{user.enabled ? 'Dezactivează' : 'Activează'}</button><button className="secondary-button" onClick={() => { setResetId(user.userId); setReset({ password: '', confirm: '' }); }}>Resetează parola</button></div>{resetId === user.userId && <div className="button-row"><input type={showResetPassword ? 'text' : 'password'} placeholder="parolă nouă" value={reset.password} onChange={(event) => setReset({ ...reset, password: event.target.value })} /><button className="ghost-button" onClick={() => setShowResetPassword(!showResetPassword)}>{showResetPassword ? 'Ascunde parola' : 'Arată parola'}</button><button className="secondary-button" onClick={generateResetPassword}>Generează</button><input type={showResetPassword ? 'text' : 'password'} placeholder="confirmă parola" value={reset.confirm} onChange={(event) => setReset({ ...reset, confirm: event.target.value })} /><button className="primary-button" onClick={() => resetPassword(user.userId)}>Salvează parola</button></div>}</section>)}
    {!error && users.length === 0 && <section className="empty-state-v2"><strong>Niciun utilizator USER</strong><span>Adaugă un cont cloud-managed; ștergerea este deferred.</span></section>}</div>;
}
export default function Users({ isAdmin = false }) { if (!api.isCloudReadOnly()) return null; if (!isAdmin) return <div className="management-page"><section className="editor-panel"><h1>Acces restricționat</h1><p>Utilizatorii sunt disponibili numai administratorilor.</p></section></div>; return <HostedUsers />; }
